# Generated by Django 3.0.5 on 2022-12-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20221129_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='topping_name',
            new_name='review',
        ),
    ]
