# Generated by Django 3.0.5 on 2022-12-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20221208_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
